name: Deploy API Service

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Setup PHP
      #   uses: shivammathur/setup-php@master
      #   with:
      #     php-version: 8.3
      #     extensions: mbstring, bcmath, zip
      #     tools: composer:v2

      - name: Setup Deployer
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dep: deploy -v
